name: "Dive CI"

on: [push]

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t sample:latest .
        
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "sample:latest"
      
      - name: Scan image
        uses: anchore/scan-action@v3
        continue-on-error: true
        with:
          image: "sample:latest"
      
      - uses: anchore/sbom-action@v0
        continue-on-error: true
        with:
          image: sample:latest

      - name: install Snyk CLI
        run: npm install -g snyk
        
      - name: run Snyk Open Source Test
        env:
          SNYK_TOKEN: "9a06072e-ba9a-4596-afeb-857a10ebbe6a"
        run: |
          npm install
          snyk auth $SNYK_TOKEN
          snyk test
